### ISSUE TITLE
Erro ao remover projeto

### ISSUE THREAD

**Issue by leogermani** [mapasculturais/mapasculturais#1086]
ao remover projeto permanentemente, erros de violação de FK:

```
PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "project" violates foreign key constraint "project_fk" on table "event"
DETAIL:  Key (id)=(57) is still referenced from table "event". in /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
#1 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(987): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(594): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM pro...', Array, Array)
#3 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(580): Doctrine\DBAL\Connection->delete('project', Array, Array)
#4 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1094): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->delete(Object(MapasCulturais\Entities\Project))
#5 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Entity.php(612): Doctrine\ORM\EntityManager->flush()
#8 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/EntitySoftDelete.php(98): MapasCulturais\Entity->delete(true)
#9 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/ControllerSoftDelete.php(39): MapasCulturais\Entities\Project->destroy(true)
#10 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(274): MapasCulturais\Controllers\Project->GET_destroy()
#11 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(176): MapasCulturais\Controller->callAction('GET', 'destroy', Array)
#12 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Project), 'destroy', Array, false)
#13 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#14 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#15 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#16 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#17 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#18 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(44): Slim\Middleware\MethodOverride->call()
#19 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
#20 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#21 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(484): Slim\Slim->run()
#22 /home/leo/devel/mapasculturais/src/index.php(4): MapasCulturais\App->run()
#23 /home/leo/devel/mapasculturais/src/router.php(27): include_once('/home/leo/devel...')
#24 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "project" violates foreign key constraint "project_fk" on table "event"
DETAIL:  Key (id)=(57) is still referenced from table "event". in /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(987): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(594): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM pro...', Array, Array)
#2 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(580): Doctrine\DBAL\Connection->delete('project', Array, Array)
#3 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1094): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->delete(Object(MapasCulturais\Entities\Project))
#4 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Entity.php(612): Doctrine\ORM\EntityManager->flush()
#7 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/EntitySoftDelete.php(98): MapasCulturais\Entity->delete(true)
#8 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/ControllerSoftDelete.php(39): MapasCulturais\Entities\Project->destroy(true)
#9 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(274): MapasCulturais\Controllers\Project->GET_destroy()
#10 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(176): MapasCulturais\Controller->callAction('GET', 'destroy', Array)
#11 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Project), 'destroy', Array, false)
#12 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#13 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#14 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#15 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#16 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#17 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(44): Slim\Middleware\MethodOverride->call()
#18 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
#19 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#20 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(484): Slim\Slim->run()
#21 /home/leo/devel/mapasculturais/src/index.php(4): MapasCulturais\App->run()
#22 /home/leo/devel/mapasculturais/src/router.php(27): include_once('/home/leo/devel...')
#23 {main}

Next Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: An exception occurred while executing 'DELETE FROM project WHERE id = ?' with params [57]:

SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "project" violates foreign key constraint "project_fk" on table "event"
DETAIL:  Key (id)=(57) is still referenced from table "event". in /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:60
Stack trace:
#0 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM pro...', Array)
#2 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(594): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM pro...', Array, Array)
#3 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(580): Doctrine\DBAL\Connection->delete('project', Array, Array)
#4 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1094): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->delete(Object(MapasCulturais\Entities\Project))
#5 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /home/leo/devel/mapasculturais/src/protected/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Entity.php(612): Doctrine\ORM\EntityManager->flush()
#8 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/EntitySoftDelete.php(98): MapasCulturais\Entity->delete(true)
#9 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/ControllerSoftDelete.php(39): MapasCulturais\Entities\Project->destroy(true)
#10 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(274): MapasCulturais\Controllers\Project->GET_destroy()
#11 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(176): MapasCulturais\Controller->callAction('GET', 'destroy', Array)
#12 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Project), 'destroy', Array, false)
#13 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#14 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#15 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#16 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#17 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#18 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(44): Slim\Middleware\MethodOverride->call()
#19 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
#20 /home/leo/devel/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#21 /home/leo/devel/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(484): Slim\Slim->run()
#22 /home/leo/devel/mapasculturais/src/index.php(4): MapasCulturais\App->run()
#23 /home/leo/devel/mapasculturais/src/router.php(27): include_once('/home/leo/devel...')
#24 {main}
```
refs #1040

**Comment by leogermani** [comment]
Acabei de testar e não aconteceu mais o erro pra mim.

Detalhe que o botão de excluir definitivamente só apareceu como opção para admin. é isso?

**Comment by marylly** [comment]
Acabei de testar e também não conseguir reproduzir @leogermani

**Comment by marcus2703** [comment]
Tentando replicar o erro, só consegui efetivar este erro inserindo campos na aba inscrição do projeto. Em outros testes a exclusão definitiva está sendo executada corretamente.
@marylly @leogermani

**Comment by leogermani** [comment]
Sim, confirmado que o erro ainda acontece
