### ISSUE TITLE
implementar botões de excluir fase do componente opportunity-phases-config

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [mapasculturais/mapasculturais#2409]
- [x] para fases de avaliação (utilizar label **excluir fase de avaliação** )
- [x] para fases de coleta de dados (utilizar label **excluir fase de coleta de dados** )
- [x] não pode ter botão na primeira e na última fase (`v-if"!phase.isFirstPhase && !phase.isLastPhase`)

- utilizar componente `<confirm-button>` que chama o método `phase.delete()`
- capturar o evento `@confirm` do confirm-button e excluir a fase da lista

**Comment by rohilario** [comment]
Erro ao excluir fase de coleta de dados:

```
Slim Application Error
The application could not run because of the following error:

Details
Type: Doctrine\ORM\ORMInvalidArgumentException
Message: Binding entities to query parameters only allowed for entities that have an identifier.
File: /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php
Line: 219
Trace
#0 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(438): Doctrine\ORM\ORMInvalidArgumentException::invalidIdentifierBindingEntity()
#1 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(453): Doctrine\ORM\AbstractQuery->processParameterValue(NULL)
#2 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(394): Doctrine\ORM\Query->resolveParameterValue(Object(Doctrine\ORM\Query\Parameter))
#3 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(316): Doctrine\ORM\Query->processParameterMappings(Array)
#4 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1073): Doctrine\ORM\Query->_doExecute()
#5 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1027): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#6 /var/www/html/protected/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(791): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#7 /var/www/html/protected/application/lib/MapasCulturais/Entities/Opportunity.php(467): Doctrine\ORM\AbstractQuery->getResult()
#8 /var/www/html/protected/application/lib/MapasCulturais/Entities/Opportunity.php(482): MapasCulturais\Entities\Opportunity->getAllRegistrations('sent')
#9 /var/www/html/protected/application/lib/MapasCulturais/Entities/Opportunity.php(978): MapasCulturais\Entities\Opportunity->getSentRegistrations()
#10 /var/www/html/protected/application/lib/MapasCulturais/Entity.php(454): MapasCulturais\Entities\Opportunity->canUserSendUserEvaluations(Object(MapasCulturais\Entities\User))
#11 /var/www/html/protected/application/lib/MapasCulturais/Entity.php(990): MapasCulturais\Entity->canUser('sendUserEvaluat...')
#12 [internal function]: MapasCulturais\Entity->jsonSerialize()
#13 /var/www/html/protected/application/lib/MapasCulturais/Controller.php(394): json_encode(Object(MapasCulturais\Entities\SpaceOpportunity))
#14 /var/www/html/protected/application/lib/MapasCulturais/Traits/ControllerSoftDelete.php(42): MapasCulturais\Controller->json(Object(MapasCulturais\Entities\SpaceOpportunity))
#15 /var/www/html/protected/application/lib/MapasCulturais/Controller.php(335): MapasCulturais\Controllers\Opportunity->ALL_destroy()
#16 /var/www/html/protected/application/lib/MapasCulturais/RoutesManager.php(169): MapasCulturais\Controller->callAction('DELETE', 'destroy', Array)
#17 /var/www/html/protected/application/lib/MapasCulturais/RoutesManager.php(107): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Opportunity), 'destroy', Array, false)
#18 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#19 /var/www/html/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#20 /var/www/html/protected/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#21 /var/www/html/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#22 /var/www/html/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#23 /var/www/html/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(47): Slim\Middleware\MethodOverride->call()
#24 /var/www/html/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
#25 /var/www/html/protected/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#26 /var/www/html/protected/application/lib/MapasCulturais/App.php(595): Slim\Slim->run()
#27 /var/www/html/index.php(4): MapasCulturais\App->run()
#28 /var/www/html/router.php(33): include_once('/var/www/html/i...')
#29 {main}
```

**Comment by rohilario** [comment]
Ajustado lógica dos botoes para verificacao se ultima ou primeira fase (buscando das props islastphase and isfirstphase).
